USE MASTER;
CREATE DATABASE BD_ViceriUniversity;

GO

USE BD_ViceriUniversity;

CREATE TABLE CURSOS(
ID INT IDENTITY,
NOME_CURSO VARCHAR(100) NOT NULL,
DESCRICAO VARCHAR(500),
DATA_INICIO DATETIME NOT NULL,
DATA_FIM DATETIME NOT NULL,
CONSTRAINT PK_CURSOS PRIMARY KEY(ID)
);

CREATE TABLE ALUNOS(
ID INT IDENTITY,
NOME VARCHAR(100) NOT NULL,
DATA_NASC DATETIME NOT NULL,
EMAIL VARCHAR(40) NOT NULL,
ID_CURSOS INT,
CONSTRAINT FK_CURSOS FOREIGN KEY (ID_CURSOS) REFERENCES CURSOS(ID),
CONSTRAINT PK_ALUNOS PRIMARY KEY(ID)
);

GO

INSERT INTO CURSOS(NOME_CURSO, DESCRICAO, DATA_INICIO, DATA_FIM) VALUES('ADMINISTRAÇÃO', 'BACHAREL', '20/03/2018', '30/04/2023');
INSERT INTO CURSOS(NOME_CURSO, DESCRICAO, DATA_INICIO, DATA_FIM) VALUES('DIREITO', 'BACHAREL', '20/03/2018', '30/04/2023');
INSERT INTO CURSOS(NOME_CURSO, DESCRICAO, DATA_INICIO, DATA_FIM) VALUES('CIENCIA DA COMPUTAÇÃO', 'BACHAREL', '20/03/2018', '30/04/2023');
INSERT INTO CURSOS(NOME_CURSO, DESCRICAO, DATA_INICIO, DATA_FIM) VALUES('ANALISE DE SISTEMAS', 'BACHAREL', '20/03/2018', '30/04/2023');
INSERT INTO CURSOS(NOME_CURSO, DESCRICAO, DATA_INICIO, DATA_FIM) VALUES('FISIOTERAPIA', 'BACHAREL', '20/03/2018', '30/04/2023');
INSERT INTO CURSOS(NOME_CURSO, DESCRICAO, DATA_INICIO, DATA_FIM) VALUES('SISTEMAS DE INFORMAÇÃO', 'BACHAREL', '20/03/2018', '30/04/2023');
